services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: examin-ai-rabbitmq
    ports:
      - "5671:5672"
      - "15671:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - examin-ai-net


  notification-postgres:
    container_name: notification-postgres
    image: postgres
    environment:
      POSTGRES_DB: notification_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - notification-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - examin-ai-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d notification_service_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-postgres:
    container_name: auth-postgres
    image: postgres
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - auth-postgres:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    expose:
      - 5433
    command: -p 5433
    networks:
      - examin-ai-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d auth_service_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "8282:80"
    networks:
      - examin-ai-net

volumes:
  rabbitmq-data:
  notification-postgres:
  auth-postgres:

networks:
  examin-ai-net:
    driver: bridge