services:

  postgres:
    image: postgres:16
    container_name: auth_postgres
    restart: always
    env_file: .env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0.5
    container_name: mongo
    restart: always
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    env_file: .env
    ports:
      - "5671:5672"
      - "15671:15672"  # management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: exam_keycloak
    restart: always
    env_file: .env
    command: start-dev
    ports:
      - "8181:8080"
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/examinai_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

#  vectordb:
#    image: qdrant/qdrant
#    container_name: vectordb
#    restart: always
#    ports:
#      - "6333:6333"
#    volumes:
#      - qdrant_data:/qdrant/storage

  pgadmin:
    image: dpage/pgadmin4
    container_name: exam_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@examinai.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
  qdrant_data:
