version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: examin-ai-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - examin-ai-net


  postgres:
    container_name: notification-service-db
    image: postgres
    environment:
      POSTGRES_DB: notification-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - examin-ai-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U notification-service-user -d notification-service" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: exam_keycloak
    restart: always
    env_file: .env
    command: start-dev
    ports:
      - "8181:8080"
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/examinai_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}


volumes:
  rabbitmq-data:
  postgres:

networks:
  examin-ai-net:
    driver: bridge

