server:
  port: 8050

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    drop-first: false
    contexts: development

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/examinai

keycloak:
  server-url: http://localhost:8181
  realm: examinai
  admin-service:
    client-id: admin-service-client
    client-secret: iCkDv9sg77qKqCUMIFTKqkS7NZLsmrb0

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
    auth-service:
      url: http://localhost:8070