server:
  port: 8050

eureka:
  instance:
    prefer-ip-address: true
#    hostname: admin-service

spring:
  datasource:
    url: jdbc:postgresql://admin-postgres:5434/admin_service_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    drop-first: false
    contexts: development

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/examinai

keycloak:
  server-url: http://keycloak:8080
  realm: examinai
  admin-service:
    client-id: admin-service-client
    client-secret: iCkDv9sg77qKqCUMIFTKqkS7NZLsmrb0

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
    auth-service:
      url: http://auth-service:8070