server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    drop-first: false
    contexts: development

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    auth:
      id: auth_listener
      queue: auth_queue
      exchange: auth_exchange
      route: auth_route

keycloak:
  server-url: http://localhost:8181
  realm: examinai
  admin:
    client-id: examinai-admin-api
    client-secret: MCVgeMd5w2Sy9r1xr2tHikLoCOROpBS4
  auth-service:
    client-id: auth-service-client
    client-secret: BecDB2enoNJ7pclu1czeKji0Smy7nwJD
  user:
    sync:
      webhook:
        url: http://localhost:8080/api/v1/auth/sync/user-event