server:
  port: 8070

eureka:
  instance:
    prefer-ip-address: true
#    hostname: auth-service

spring:
  datasource:
    url: jdbc:postgresql://auth-postgres:5433/auth_service_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    drop-first: false
    contexts: development

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin123
    auth:
      id: auth_listener
      queue: auth_queue
      exchange: auth_exchange
      route: auth_route

keycloak:
  server-url: http://keycloak:8080
  realm: examinai
  admin:
    client-id: examinai-admin-api
    client-secret: MCVgeMd5w2Sy9r1xr2tHikLoCOROpBS4
  auth-service:
    client-id: auth-service-client
    client-secret: Q2wdvNAlXLxtj0hlvDmi4Kvwl9ljI3BJ