server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
#    hostname: gateway-service

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RemoveRequestHeader=Cookie
            - AddRequestHeader=Authorization, Bearer

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification-threads/**
          filters:
            - RemoveRequestHeader=Cookie
            - AddRequestHeader=Authorization, Bearer

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/v1/course/**, /api/v1/program/**, /api/v1/task/**
          filters:
            - RemoveRequestHeader=Cookie
            - AddRequestHeader=Authorization, Bearer

        - id: discovery-service
          uri: http://discovery-service:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
            - RemoveRequestHeader=Cookie

        # For getting HTML&CSS properties of the Eureka server page
        - id: discovery-service-static
          uri: http://discovery-service:8761
          predicates:
            - Path=/eureka/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: examinai-gateway
            client-name: Keycloak
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/examinai
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/examinai

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.server: DEBUG
