server:
  port: 8060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    drop-first: false
    contexts: development

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/examinai

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    auth:
      id: auth_listener
      queue: auth_queue
      exchange: auth_exchange
      route: auth_route
    email:
      id: email_listener
      queue: email_queue
      exchange: email_exchange
      route: email_route

  mail:
    host: smtp.gmail.com
    port: 587
    username: your@gmail.com
    password: "app password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000